CREATE TABLE `users` (
  `USER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_NAME` varchar(50) NOT NULL,
  `USER_EMAIL` varchar(150) NOT NULL,
  `USER_FIRST` int(11) NOT NULL,
  `USER_:LAST` int(11) NOT NULL,
  `USER_BIO` text NOT NULL,
  `USER_DOB` date NOT NULL,
  `USER_JOINED` datetime NOT NULL,
  `USER_LAST_IP` varchar(30) NOT NULL,
  `USER_ACTIVE` int(11) NOT NULL,
  PRIMARY KEY (`USER_ID`)
);

CREATE  TABLE `salt` (
  `SALT_USER` INT NOT NULL ,
  `SALT_KEY` VARCHAR(45) NOT NULL ,
  PRIMARY KEY (`SALT_USER`, `SALT_KEY`) );